name: HTML Validator
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Html5Validator
        uses: cygnetdigital/html5validator-action@master
        with:
          root-subdirectory: .
