name: HTML Validator
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check HTML
        uses: anishathalye/proof-html@v1
        with:
          directory: .
